export { default as DashboardPage } from './DashboardPage';
export { default as NAVSystemPage } from './NAVSystemPage';
export { default as AssetsManagementPage } from './AssetsManagementPage';
export { default as TradersManagementPage } from './TradersManagementPage';
export { default as OfficersManagementPage } from './OfficersManagementPage';
export { default as KYCManagementPage } from './KYCManagementPage';
export { default as AnalyticsPage } from './AnalyticsPage';
export { default as ReportsPage } from './ReportsPage';
export { default as NotificationsCenterPage } from './NotificationsCenterPage';
